# Generated by Django 5.0.7 on 2024-07-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
